### ISSUE TITLE
sp_repo_review: false positive and false negative mypy checks

### ISSUE THREAD

**Issue by Saransh-cpp** [scientific-python/cookie#386]
The `MY101` and `MY102` have been passing and failing (respectively) on the develop branch of PyBaMM, but it should be the other way.

Running sp_repo_review: https://learn.scientific-python.org/development/guides/repo-review/?repo=pybamm-team%2FPyBaMM&branch=develop

Actual mypy config: https://github.com/pybamm-team/PyBaMM/blob/94aa498176d0b6bb1186aa63bebd9c85f7b74bff/pyproject.toml#L272-L282

I noticed that running the develop version of `sp_repo_review` and `repo_review` does not give these false results. Please feel free to close this if this has been fixed but has not been released. Thanks!

**Comment by henryiii** [comment]
Just started a new release. Could you see if it still persists?

**Comment by henryiii** [comment]
I'm not sure what's wrong with these checks in WebAssembly, but they aren't working correctly (only in WebAssembly).

**Comment by DimitriPapadopoulos** [comment]
Likewise, the `MY102` failure on  [abravalheri/validate-pyproject](https://github.com/abravalheri/validate-pyproject) looks like a false positive:

https://learn.scientific-python.org/development/guides/repo-review/?repo=abravalheri%2Fvalidate-pyproject&branch=main

[**validate-pyproject/pyproject.toml**](https://github.com/abravalheri/validate-pyproject/blob/e1aa94607ce086991e6b37b09cae3dfb3c623c8a/pyproject.toml#L10-L19)
Lines 10 to 19 in [`e1aa946`](https://github.com/abravalheri/validate-pyproject/commit/e1aa94607ce086991e6b37b09cae3dfb3c623c8a)
```toml
[tool.mypy]
show_traceback = true
strict = true
# Scaling back on some of the strictness for now
disallow_any_generics = false
disallow_subclassing_any = false

[[tool.mypy.overrides]]
module = ["fastjsonschema"]
ignore_missing_imports = true
```
