### ISSUE TITLE
Deprecate `prettier` pre-commit hook

### ISSUE THREAD

**Issue by ariostas** [scientific-python/cookie#439]
The `prettier` pre-commit hook has been [deprecated](https://github.com/pre-commit/pre-commit.com/pull/953) and the [repo](https://github.com/pre-commit/mirrors-prettier) has been archived since `prettier` made some breaking changes.

**Comment by ariostas** [comment]
They have some alternatives [here](https://prettier.io/docs/en/precommit.html), but none of them seem particularly convenient.

**Comment by kratsg** [comment]
I'm using

```
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.3.2"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript] #, json]
        args: [--prose-wrap=always]
```

this seems to be maintained for now...
