### ISSUE TITLE
[FYI] Pytest have "weak recommendation" on `addopts` to be a string

### ISSUE THREAD

**Issue by abravalheri** [scientific-python/cookie#465]
As per the discussion in https://github.com/pytest-dev/pytest/issues/12228, it seems that `pytest` recommends the `addopts` setting to be a string (although that is pretty much a temporary hack due to transitory nature of `tool.pytest.ini_options`).

https://github.com/scientific-python/cookie/blob/fea6e2f8f88f5b25e14efada9872acd6c89e02d9/docs/pages/guides/pytest.md?plain=1#L76

**Comment by henryiii** [comment]
I don't gather that from the discussion. The person who suggested it be a string also suggested it not be in pyproject.toml. Since this isn't supported:

```toml
[tool.pytest.ini_options]
addopts = """
    # show 10 slowest invocations:
    --durations=10

    # a bit of verbosity doesn't hurt:
    -v
"""
```

but this is:


```toml
[tool.pytest.ini_options]
addopts = [
    # show 10 slowest invocations:
    "--durations=10",

    # a bit of verbosity doesn't hurt:
    "-v",
]
```

I'd say it's significantly better to have it as a list of strings.

> transitory nature

It's been several years now.
