### ISSUE TITLE
PY007: allow/support Pixi

### ISSUE THREAD

**Issue by lucascolley** [scientific-python/cookie#496]
PY007 should pass if a project has a `pixi.toml` or the equivalent sections in `pyproject.toml`. Bonus points if this could be an option when generating a project with cookie!

**Comment by lucascolley** [comment]
https://github.com/data-apis/array-api-extra is an example of a fresh cookie hatchling project which I have modified to use pixi instead of nox. (thanks by the way, I love that this tool exists!)

**Comment by henryiii** [comment]
If pixi tasks are missing, it's an oversight (and I would have sworn I added them some time ago...). I was just thinking about adding the option when generating a cookie, I helped someone yesterday set up a pixi project with this template!

**Comment by lucascolley** [comment]
great, thanks!

**Comment by henryiii** [comment]
I'm guessing the key bits are:

```toml
[tool.pixi.project]
name = "array-api-extra"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[tool.pixi.pypi-dependencies]
array-api-extra = { path = ".", editable = true }

[tool.pixi.tasks]
pre-commit = { cmd = "pre-commit install && pre-commit run -v --all-files --show-diff-on-failure" }

[tool.pixi.feature.lint.dependencies]
pylint = "*"

[tool.pixi.feature.lint.tasks]
pylint = { cmd = ["pylint", "array_api_extra"], cwd = "src" }
lint = { depends-on = ["pre-commit", "pylint"] }

[tool.pixi.feature.test.dependencies]
pytest = ">=6"
pytest-cov = ">=3"

[tool.pixi.feature.test.tasks]
test = { cmd = "pytest" }
test-ci = { cmd = "pytest -ra --cov --cov-report=xml --cov-report=term --durations=20" }

[tool.pixi.feature.dev.dependencies]
pytest = ">=6"
pytest-cov = ">=3"
pylint = "*"

[tool.pixi.feature.docs.dependencies]
sphinx = ">=7.0"
furo = ">=2023.08.17"

[tool.pixi.feature.docs.pypi-dependencies]
myst_parser = ">=0.13"
sphinx_copybutton = "*"
sphinx_autodoc_typehints = "*"

[tool.pixi.feature.py309.dependencies]
python = "~=3.9.0"

[tool.pixi.feature.py312.dependencies]
python = "~=3.12.0"

[tool.pixi.environments]
default = { solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
dev = { features = ["dev", "docs"], solve-group = "default" }
ci-py309 = ["py309", "test"]
ci-py312 = ["py312", "test"]
```

and

```yaml
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.30.0
          cache: true
          environments: ${{ matrix.environment }}

      - name: Test package
        run: pixi run -e ${{ matrix.environment }} test-ci
```

**Comment by henryiii** [comment]
Why do you need the name? That should get picked up from project.name? 

I think pre-commit task installing pre-commit hooks and running pre-commit is a little odd. I think I missed copying the pre-commit env above, somehow.

cache: true is the default, I think, for the action?

**Comment by lucascolley** [comment]
Yep. You might want to start by just seeing what `pixi init` gives you on the generated `pyproject.toml`. I followed https://pixi.sh/latest/advanced/pyproject_toml/ and https://pixi.sh/latest/advanced/github_actions/.

> Why do you need the name? That should get picked up from project.name?

I think you're right, that looks unnecessary.

**Comment by henryiii** [comment]
Core issue is in (PY007 support).

Proper pixi support might need to wait till we can use all PEP 621 backends (Poetry being the current standout).

**Comment by cheginit** [comment]
Thought I add how I use Pixi in case official support is being added for Pixi. Note that these configs use `optional-dependencies` in `pyproject.toml`, so there's no need to specify the deps in the Pixi section. 

When `maturin` is being used and benchmarking with `codspeed`:

```toml
[tool.maturin]
# "extension-module" tells pyo3 we want to build an
# extension module (skips linking against libpython.so)
features = [ "pyo3/extension-module", "python" ]
module-name = "catsmoothing._catsmoothing"
# Bindings type
bindings = "pyo3"
# Strip the library for minimum file size
strip = true
# Build artifacts with the specified Cargo profile
profile = "release"

[tool.pixi.project]
channels = [ "conda-forge" ]
platforms = [ "linux-64", "osx-64", "osx-arm64", "win-64" ]

[tool.pixi.pypi-dependencies]
catsmoothing = { path = ".", editable = true }

[tool.pixi.feature.py310.dependencies]
python = "~=3.10.0"
maturin = "*"
uv = "*"
pip = "*"

[tool.pixi.feature.py313.dependencies]
python = "~=3.13.0"
maturin = "*"
uv = "*"
pip = "*"

[tool.pixi.environments]
dev = { features = [ "dev", "py313" ] }
test310 = { features = [ "test", "py310" ] }
test313 = { features = [ "test", "py313" ] }
benchmark = { features = [ "benchmark", "py313" ] }
typecheck = { features = [ "typecheck", "py313" ] }
lint = { features = [ "lint", "py313" ], no-default-feature = true }
docs = { features = [ "docs", "py313" ] }

[tool.pixi.tasks]
preinstall = "maturin develop --uv"

[tool.pixi.feature.test.tasks]
test = { cmd = [
  "pytest",
  "--cov",
  "--cov-append",
  "--cov-branch",
  "--cov-report=xml",
  "--junitxml=junit.xml",
  "--durations=5",
], depends-on = [ "preinstall" ] }
report = { cmd = [ "coverage", "report" ], depends-on = [ "test" ] }
html = { cmd = [ "coverage", "html" ], depends-on = [ "report" ] }

[tool.pixi.feature.benchmark.tasks]
benchmark = { cmd = [ "pytest", "catsmoothing/tests", "--codspeed" ], depends-on = [ "preinstall" ] }

[tool.pixi.feature.lint.tasks]
lint = "pre-commit run --all-files"
pcupdate = "pre-commit autoupdate"
spell = "codespell -w"

[tool.pixi.feature.typecheck.tasks]
typecheck = { cmd = [ "pyright" ], depends-on = [ "preinstall" ] }

[tool.pixi.feature.docs.tasks]
build-docs = "mkdocs build --strict"
docs = { cmd = [ "mkdocs", "serve" ], depends-on = [ "preinstall", "build-docs" ] }
```

For pure python projects with geospatial dependencies and benchmarking with `codspeed`:

```toml
[tool.pixi.project]
channels = [ "conda-forge" ]
platforms = [ "linux-64", "osx-64", "osx-arm64", "win-64" ]

[tool.pixi.pypi-dependencies]
sceua = { path = ".", editable = true }

[tool.pixi.feature.py310.dependencies]
hdf5 = "*"
libnetcdf = "*"
proj = "*"
libgdal-core = "*"
python = "~=3.10.0"
uv = "*"

[tool.pixi.feature.py313.dependencies]
hdf5 = "*"
libnetcdf = "*"
proj = "*"
libgdal-core = "*"
python = "~=3.13.0"
uv = "*"

[tool.pixi.environments]
test310 = { features = [ "test", "py310" ] }
test313 = { features = [ "test", "py313" ] }
dev = { features = [ "dev", "py313" ] }
benchmark = { features = [ "benchmark", "py313" ] }
typecheck = { features = [ "typecheck", "py313" ] }
docs = { features = [ "docs", "dev", "py313" ] }
lint = { features = [ "lint", "py313" ], no-default-feature = true }

[tool.pixi.feature.test.tasks]
test = { cmd = [
  "pytest",
  "--cov",
  "--cov-append",
  "--cov-branch",
  "--cov-report=xml",
  "--junitxml=junit.xml",
  "--durations=5",
] }
report = { cmd = [ "coverage", "report" ], depends-on = [ "test" ] }
html = { cmd = [ "coverage", "html" ], depends-on = [ "report" ] }

[tool.pixi.feature.benchmark.tasks]
benchmark = "pytest tests --codspeed"

[tool.pixi.feature.lint.tasks]
lint = "pre-commit run --all-files"
pcupdate = "pre-commit autoupdate"
spell = "codespell -w"

[tool.pixi.feature.typecheck.tasks]
typecheck = "pyright"

[tool.pixi.feature.docs.tasks]
build-docs = "mkdocs build --strict"
docs = { cmd = [ "mkdocs", "serve" ], depends-on = [ "build-docs" ] }
```

For basic pure python projects and no benchmarking:

```toml
[tool.pixi.project]
channels = [ "conda-forge" ]
platforms = [ "linux-64", "osx-64", "osx-arm64", "win-64" ]

[tool.pixi.pypi-dependencies]
pywbt = { path = ".", editable = true }

[tool.pixi.feature.py39.dependencies]
python = "~=3.9.0"
uv = "*"

[tool.pixi.feature.py313.dependencies]
python = "~=3.13.0"
uv = "*"

[tool.pixi.environments]
dev = { features = [ "dev", "py313" ] }
test39 = { features = [ "test", "dem", "cli", "py39" ] }
test313 = { features = [ "test", "dem", "cli", "py313" ] }
typecheck = { features = [ "typecheck", "dem", "cli", "py313" ] }
lint = { features = [ "lint", "py313" ], no-default-feature = true }
docs = { features = [ "docs", "py313" ] }

[tool.pixi.feature.test.tasks]
test = "pytest"
report = { cmd = [ "coverage", "report" ], depends-on = [ "test" ] }
html = { cmd = [ "coverage", "html" ], depends-on = [ "report" ] }

[tool.pixi.feature.lint.tasks]
lint = "pre-commit run --all-files"
pcupdate = "pre-commit autoupdate"
spell = "codespell -w"

[tool.pixi.feature.typecheck.tasks]
typecheck = "pyright"

[tool.pixi.feature.docs.tasks]
build-docs = "mkdocs build --strict"
docs = { cmd = [ "mkdocs", "serve" ], depends-on = [ "build-docs" ] }
```
