### ISSUE TITLE
codecov step needs a slug name now?

### ISSUE THREAD

**Issue by kratsg** [scientific-python/cookie#551]
It seems codecov updated a little, and the recommended set up now looks like

```yaml
- name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v5
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
      slug: scipp-atlas/atlas-schema
```

as opposed to without the slug.
